language: node_js

node_js:
    - node

before_script:
    - npm run build

after_success:
    - npx codecov

deploy:
    provider: npm
    email: lodovico@giaretart.net
    api_key: NPM_TOKEN
    on:
        tags: true

cache:
    directories:
        - node_modules